### ISSUE TITLE
TextEmbed incompatible with Urwid 2.5.3

### ISSUE THREAD

**Issue by danschwarz** [AnonymouX47/urwidgets#1]
**Description**
See issue in Urwid 

https://github.com/urwid/urwid/issues/802

**Comment by AnonymouX47** [comment]
`TextEmbed` should work as good as before now. Alongside the fix, I added the ability to override the codepoints used for widget placeholders.

I just want to include a couple more updates and release at once.

Thanks.

**Comment by AnonymouX47** [comment]
Released [v0.2.0](https://github.com/AnonymouX47/urwidgets/releases/tag/v0.2.0).
